#!/bin/bash

# Import do ShellBot
source ShellBot.sh
bot_token=""

# Inicia o bot
ShellBot.init --token "$bot_token"

# Mensagem de welcome
mostrar_mensagem(){
    local msg

    msg="[@${message_new_chat_member_username[$id]:-null}]\n"
    msg+="Falai *${message_new_chat_member_first_name[$id]}*"'!!\n\n'
    msg+="Eu sou o robô [@$(ShellBot.username)]"

    # Enviar mendagem de boas vindas.
    ShellBot.sendMessage --chat_id ${message_chat_id[$id]} \
                                                        --text "$(echo -e $msg)"
                                                        --parse_mode markdown
}

while : ; do
    # Obter atualizações
    ShellBot.getUpdates --limit 100 --offset $(ShellBot.OffsetNext) --timeout 30

    # Listar o indice das atualizações
    for id in $(ShellBot.ListUpdates) ; do
        # Inicio thread
        (
            echo -e "Executou" >> mxlr.log
            [[ ${message_new_chat_member_id[$id]} ]] && mostrar_mensagem

            # Menu
            case ${message_text[$id]} in
                *)
                    
                ;;
            esac
        ) &
    done

done